// <auto-generated />
using System;
using FinancialPlanner.Blazor.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialPlanner.Blazor.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260130133522_AddUsersAndCategories")]
    partial class AddUsersAndCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.BankStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalOutgoing")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.HasIndex("UserId");

                    b.ToTable("BankStatements");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Expenditure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ExpenseCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<bool>("Recurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseCategoryId");

                    b.HasIndex("MonthId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenditures");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.ExpenseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ExpenseCategories");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IncomeCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncomeType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MyProperty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("Date");

                    b.Property<bool>("Recurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncomeCategoryId");

                    b.HasIndex("MonthId");

                    b.HasIndex("UserId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.IncomeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IncomeCategories");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualSavings")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualTotalExpenditure")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualTotalIncome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProjectedSavings")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProjectedTotalExpenditure")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProjectedTotalIncome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefaultSavingsTarget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PaydayDayOfMonth")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.BankStatement", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.Month", "Month")
                        .WithMany("BankStatements")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithMany("BankStatements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Month");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Expenditure", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.ExpenseCategory", "Category")
                        .WithMany("Expenditures")
                        .HasForeignKey("ExpenseCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.Month", "Month")
                        .WithMany("Expenditures")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithMany("Expenditures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Month");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.ExpenseCategory", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithMany("ExpenseCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Income", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.IncomeCategory", "Category")
                        .WithMany("Incomes")
                        .HasForeignKey("IncomeCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.Month", "Month")
                        .WithMany("Incomes")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");

                    b.Navigation("Month");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.IncomeCategory", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithMany("IncomeCategories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Month", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithMany("Months")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.UserProfile", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FinancialPlanner.Blazor.DataAccess.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.ExpenseCategory", b =>
                {
                    b.Navigation("Expenditures");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.IncomeCategory", b =>
                {
                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Month", b =>
                {
                    b.Navigation("BankStatements");

                    b.Navigation("Expenditures");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.User", b =>
                {
                    b.Navigation("BankStatements");

                    b.Navigation("Expenditures");

                    b.Navigation("ExpenseCategories");

                    b.Navigation("IncomeCategories");

                    b.Navigation("Incomes");

                    b.Navigation("Months");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
