// <auto-generated />
using System;
using FinancialPlanner.Blazor.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialPlanner.Blazor.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20251011100205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Expenditure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Expenditures");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Recurring")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Savings")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalExpenditure")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Expenditure", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.Month", null)
                        .WithMany("Expenditures")
                        .HasForeignKey("MonthId");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Income", b =>
                {
                    b.HasOne("FinancialPlanner.Blazor.DataAccess.Models.Month", null)
                        .WithMany("Incomes")
                        .HasForeignKey("MonthId");
                });

            modelBuilder.Entity("FinancialPlanner.Blazor.DataAccess.Models.Month", b =>
                {
                    b.Navigation("Expenditures");

                    b.Navigation("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
